### ISSUE TITLE
Does not format certain XML feeds

### ISSUE THREAD

**Issue by bananabrann** [jynolen/splunk_xml_formatter#1]
Hi there! I'm loving your XML formatter, but it unfortunately does not work on a lot of big XML feeds I'm running in to.

One I can share is the public National Weather Service (NWS) XML feed. 
https://alerts.weather.gov/cap/us.php?x=0

Chrome 73.0.3683.103 (Official Build) (64-bit)
JavaScript V8 7.3.492.27

**Comment by johnvox** [comment]
Hello !
Thank you for your review.
Can you please provide raw XML source of the event, and eventually error in the JS code ?

Thank you.

**Comment by johnvox** [comment]
Hello,
I check your XML Feed, for what i see this is a full XML Page.
Can you confirm that "All the page" is in one single event ?

Depending of this I will try 2 things
1. Try with the full page as 1 single event
2. Try with only the root node and all sub-content in 1 single event (here in our exemple the event will begin with <feed\n

I keep you update on this

**Comment by johnvox** [comment]
Resolve by #2

**Comment by bananabrann** [comment]
Thanks for replying! Sorry about the latency –I completely missed your first message. @jynolen 

When you say "raw XML", do you want just the actual text printed on the screen? It's quite lengthy. 

I unfortunately cannot confirm anything on the backend, as I don't have the capability to change and/or publish anything from weather.gov

**Comment by johnvox** [comment]
Hello @bananabrann,
Sorry too, only see your comment now :(
I made some changes in the extension can you confirm the new version solve your issue ?

**Comment by bananabrann** [comment]
Hey @jynolen, again, I'm sorry I've been bad at responding. I'm starting to use GitHub more often, so I'll on more.
XML is still not formatting for me. Am I missing something? 
![Screen Shot 2019-10-11 at 4 40 07 PM](https://user-images.githubusercontent.com/43423455/66683580-cdbb1800-ec45-11e9-9d0f-347fcd35d954.png)
